### ISSUE TITLE
With external Writer class temp dir not  working

### ISSUE THREAD

**Issue by wagy** [aVadim483/fast-excel-writer#105]
Version : 6.4.1
Please change this line in the Excel constructor

<img width="1288" alt="Image" src="https://github.com/user-attachments/assets/993402bf-18da-4276-b92e-6cc30603dede" />

**Comment by mbraeuner** [comment]
I think `!empty()` is not enough, because the $tempDir is maybe not initialized and cannot be accessed before initialization. see #107

**Comment by aVadim483** [comment]
It seems the problem has been solved

**Comment by wagy** [comment]
No, is not solved on Excel.php  change line 187

old:   if (self::$tempDir) {
new: if (!empty(self::$tempDir)) {

see on line 172  this is correct !!

**Comment by aVadim483** [comment]
in v.6.5.1
